"""
Defines constants for named column indices to converter matrix.

Some examples of usage, after defining the constants using the line above,
are::

    Pg = convdc[4, PCONV];         # get the real power output of convertor 4
    convdc[:, CONVTYPE_AC] = PVC;  # set all converters in voltage controlling mode

The index, name and meaning of each column of the branch matrix is given
below:

columns 0-19 must be included in input matrix (in case file)
    0.  C{CONV_BUS}    converter bus number (dc bus numbering)
    1.  C{CONVTYPE_DC} dc bus type (1 = constant power, 2 = dc slack, 3 = dc voltage droop)
    2.  C{CONVTYPE_AC} ac bus type (1 = PQ, 2 = PV)
    3.  C{PCONV}       Ps, active power injected in the ac grid (MW)
    4.  C{QCONV}       Qs, reactive power injected in the ac grid (MVAr)
    5.  C{VCONV}       Vtar, target voltage of converter connected ac bus (p.u.)
    6.  C{RTF}       	rtf, transformer resistance (p.u.)
    7.  C{XTF}         xtf, transformer reactance (p.u.)
    8.  C{BF}          bf, filter susceptance (p.u.)
    9.  C{RCONV}       rc, phase reactor resistance (p.u.)
   10.  C{XCONV}       xc, phase reactor reactance (p.u.)
   11.  C{BASEKVC}     converter baseKV, base voltage (kV)
   12.  C{VCMAX}       maxVc, maximum converter voltage magnitude (p.u.)
   13.  C{VCMIN}       minVc, minimum converter voltage magnitude (p.u.)
   14.  C{ICMAX}       Imax, maximum converter current (p.u.)
   15.  C{CONVSTATUS}  converter status (1 = on, 0 = off)
   16.  C{LOSSA}       LossA, constant loss coefficient (MW)
   17.  C{LOSSB}       LossB, linear loss coefficient(kV) 
   18.  C{LOSSCR}      LossCrec, rectifier quadratic loss coefficient (Ohm)
   19.  C{LOSSCI}      LossCinv, inverter quadratic loss coefficient (Ohm)
    
columns 20-23 (droop control) can be included in input matrix (in case file)
they are typically not present in the input matrix
    20. C{DROOP}       dc voltage droop (MW/p.u)
    21. C{PDCSET}      voltage droop power set-point (MW)
    22. C{VDCSET}      voltage droop voltage set-point (p.u.)
    23. C{DVDCSET}     voltage droop deadband (p.u.) (optional)
    
columns 24-33 are added to matrix after the power flow solution
they are typically not present in the input matrix
    24. C{VMC}         Vm_C, converter voltage magnitude (p.u.)
    25. C{VAC}         Va_C, converter voltage angle (degrees)
    26. C{PCCONV}      Pc, active power generated by the converter (MW)
    27. C{QCCONV}      Qc, reactive power generated by the converter (MVAr)
    28. C{PCLOSS}      Pl, active converter power losses (MW)
    29. C{VMF}         Vm_F, filter voltage magnitude (p.u.)
    30. C{VAF}         Va_F, filter voltage angle (degrees)
    31. C{PFIL}        Psf or Pcf, active power at filter bus (MW)
    32. C{QCONVF}      Qsf, reactive power through transformer at filter bus (MVAr)
    33. C{QCCONVF}     Qcf, reactive power through reactor at filter bus (MVAr)

additional constants, used to assign/compare values in the CONVTYPE_DC 
and CONVTYPE_AC column
     3. C{DCDROOP}     dc voltage droop
     2. C{DCSLACK}     dc slack bus
     1. C{DCNOSLACK}   constant active power bus    
     2. C{PVC}         constant voltage converter control
     1. C{PQC}         constant reactive power converter control
    
@author:Jef Beerten (KU Leuven)
@author:Roni Irnawan (Aalborg University)    
"""

# define bus types
DCDROOP     = 3     # dc voltage droop 
DCSLACK     = 2     # dc slack bus
DCNOSLACK   = 1     # constant active power slack bus
PVC         = 2     # constant voltage converter control
PQC         = 1     # constant reactive power converter control

# define the indices
CONV_BUS    =  0    # converter bus number (dc bus numbering)
CONVTYPE_DC =  1    # dc bus type (1 = constant power, 2 = dc slack)
CONVTYPE_AC =  2    # ac bus type (1 = PQ, 2 = PV)
PCONV       =  3    # P, active power injected in the ac grid (MW)
QCONV       =  4    # Q, reactive power injected in the ac grid (MVAr)
VCONV       =  5    # Vtar, target voltage of converter connected ac bus (p.u.)
RTF         =  6    # rtf, transformer resistance (p.u.)
XTF         =  7    # xtf, transformer reactance (p.u.)
BF          =  8    # bf, filter susceptance (p.u.)
RCONV       =  9    # rc, phase reactor resistance (p.u.)
XCONV       = 10    # xc, phase reactor reactance (p.u.)
BASEKVC     = 11    # converter baseKV, base voltage (kV)
VCMAX       = 12    # maxVc, maximum converter voltage magnitude (p.u.)
VCMIN       = 13    # minVc, minimum converter voltage magnitude (p.u.)
ICMAX       = 14    # Imax, maximum converter current (p.u.)
CONVSTATUS  = 15    # converter status (1 = on, 0 = off)
LOSSA       = 16    # LossA, constant loss coefficient  (MW)
LOSSB       = 17    # LossB, linear loss coefficient    (kV) 
LOSSCR      = 18    # LossCrec, rectifier quadratic loss coefficient (Ohm)
LOSSCI      = 19    # LossCinv, inverter quadratic loss coefficient (Ohm)

# columns only have to be included when a voltage droop operation is considered
DROOP       = 20    # dc voltage droop (p.u/MW)
PDCSET      = 21    # voltage droop power set-point (MW)
VDCSET      = 22    # voltage droop voltage set-point (p.u.)
DVDCSET     = 23    # voltage droop deadband (p.u.)

# included in pf solution, not necessarily in input
VMC         = 24    # Vm_C, converter voltage magnitude (p.u.)
VAC         = 25    # Va_C, converter voltage angle (degrees)
PCCONV      = 26    # Pc, active power generated by the converter (MW)
QCCONV      = 27    # Qc, reactive power generated by the converter (MVAr)
PCLOSS      = 28    # Pl, active converter power losses (MW)
VMF         = 29    # Vm_F, filter voltage magnitude (p.u.)
VAF         = 30    # Va_F, filter voltage angle (degrees)
PFIL        = 31    # Psf or Pcf, active power at filter bus (MW)
QCONVF      = 32    # Qsf, reactive power through transformer at filter bus (MVAr)
QCCONVF     = 33    # Qcf, reactive power through reactor at filter bus (MVAr)
